/
/_static/classic.css
/library/index.html
/c-api/index.html
/license.html
/py-modindex.html
/installing/index.html
/faq/index.html
/genindex.html
/whatsnew/index.html
/glossary.html
/_static/pygments.css
/_static/py.png
/copyright.html
/_static/opensearch.xml
/search.html
/whatsnew/2.7.html
/reference/index.html
/bugs.html
/using/index.html
/contents.html
/distributing/index.html
/about.html
/download.html
/tutorial/index.html
/extending/index.html
/howto/index.html
/library/sys.html
/library/imghdr.html
/library/2to3.html
/library/mimetools.html
/library/cmath.html
/library/urllib.html
/library/carbon.html
/library/sun.html
/library/mimetypes.html
/library/atexit.html
/library/telnetlib.html
/library/socketserver.html
/library/string.html
/library/xml.dom.html
/library/windows.html
/library/decimal.html
/library/imageop.html
/library/aetypes.html
/library/datetime.html
/library/collections.html
/library/sgmllib.html
/library/re.html
/library/site.html
/library/userdict.html
/library/urllib2.html
/library/gzip.html
/library/plistlib.html
/library/signal.html
/library/pyclbr.html
/library/xml.etree.elementtree.html
/library/compileall.html
/library/xdrlib.html
/library/filecmp.html
/library/httplib.html
/library/argparse.html
/library/aifc.html
/library/pdb.html
/library/stat.html
/library/ttk.html
/library/urlparse.html
/library/imaplib.html
/library/popen2.html
/library/profile.html
/library/mimify.html
/library/imp.html
/library/threading.html
/library/idle.html
/library/termios.html
/library/filesys.html
/library/rlcompleter.html
/library/docxmlrpcserver.html
/library/difflib.html
/library/sched.html
/library/nntplib.html
/library/scrolledtext.html
/library/array.html
/library/ensurepip.html
/library/curses.html
/library/logging.handlers.html
/library/fractions.html
/library/xml.sax.reader.html
/library/imgfile.html
/library/cmd.html
/library/shelve.html
/library/tkinter.html
/library/cgitb.html
/library/easydialogs.html
/library/hmac.html
/library/modulefinder.html
/library/random.html
/library/queue.html
/library/simplexmlrpcserver.html
/library/debug.html
/library/thread.html
/library/macos.html
/library/grp.html
/library/unicodedata.html
/library/binascii.html
/library/colorpicker.html
/library/operator.html
/library/tty.html
/library/getopt.html
/library/sunaudio.html
/library/zlib.html
/library/audioop.html
/library/pkgutil.html
/library/formatter.html
/library/md5.html
/library/rexec.html
/library/curses.panel.html
/library/symtable.html
/library/getpass.html
/library/winsound.html
/library/trace.html
/library/shlex.html
/library/ossaudiodev.html
/library/asynchat.html
/library/json.html
/library/__main__.html
/library/mm.html
/library/test.html
/library/ssl.html
/library/datatypes.html
/library/functools.html
/library/configparser.html
/library/timeit.html
/library/distutils.html
/library/__future__.html
/library/cookielib.html
/library/bisect.html
/library/copy.html
/library/mailbox.html
/library/code.html
/library/shutil.html
/library/weakref.html
/library/allos.html
/library/struct.html
/library/gdbm.html
/library/gensuitemodule.html
/library/dircache.html
/library/new.html
/library/binhex.html
/library/xml.sax.html
/library/modules.html
/library/persistence.html
/library/doctest.html
/library/spwd.html
/library/importlib.html
/library/distribution.html
/library/optparse.html
/library/pyexpat.html
/library/mailcap.html
/library/types.html
/library/repr.html
/library/constants.html
/library/stringprep.html
/library/sqlite3.html
/library/quopri.html
/library/dummy_threading.html
/library/crypto.html
/library/numeric.html
/library/bsddb.html
/library/rfc822.html
/library/mimewriter.html
/library/functions.html
/library/smtpd.html
/library/python.html
/library/bastion.html
/library/i18n.html
/library/restricted.html
/library/subprocess.html
/library/development.html
/library/strings.html
/library/mmap.html
/library/wsgiref.html
/library/tempfile.html
/library/os.path.html
/library/asyncore.html
/library/ipc.html
/library/webbrowser.html
/library/fpectl.html
/library/copy_reg.html
/library/multifile.html
/library/basehttpserver.html
/library/codeop.html
/library/statvfs.html
/library/xml.dom.pulldom.html
/library/turtle.html
/library/tk.html
/library/othergui.html
/library/stringio.html
/library/nis.html
/library/syslog.html
/library/logging.html
/library/mutex.html
/library/uuid.html
/library/time.html
/library/misc.html
/library/warnings.html
/library/hashlib.html
/library/gettext.html
/library/xml.sax.handler.html
/library/htmlparser.html
/library/frameworks.html
/library/symbol.html
/library/undoc.html
/library/aetools.html
/library/cgihttpserver.html
/library/posixfile.html
/library/posix.html
/library/marshal.html
/library/platform.html
/library/calendar.html
/library/netdata.html
/library/aepack.html
/library/readline.html
/library/ctypes.html
/library/email.html
/library/fpformat.html
/library/os.html
/library/tix.html
/library/resource.html
/library/pwd.html
/library/xml.html
/library/msvcrt.html
/library/base64.html
/library/uu.html
/library/cd.html
/library/hotshot.html
/library/ic.html
/library/mhlib.html
/library/mac.html
/library/intro.html
/library/fileinput.html
/library/pickle.html
/library/dbhash.html
/library/xmlrpclib.html
/library/pickletools.html
/library/htmllib.html
/library/macosa.html
/library/al.html
/library/zipfile.html
/library/_winreg.html
/library/keyword.html
/library/locale.html
/library/select.html
/index.html
/library/whichdb.html
/library/xml.sax.utils.html
/library/runpy.html
/_sources/library/index.txt
/library/imputil.html
/library/autogil.html
/library/poplib.html
/library/codecs.html
/library/linecache.html
/library/contextlib.html
/library/dbm.html
/library/compiler.html
/library/jpeg.html
/library/simplehttpserver.html
/reference/grammar.html
/library/dl.html
/library/itertools.html
/library/bdb.html
/library/sndhdr.html
/library/math.html
/library/dumbdbm.html
/library/tabnanny.html
/library/anydbm.html
/library/py_compile.html
/library/ftplib.html
/library/unix.html
/library/multiprocessing.html
/library/sgi.html
/library/sets.html
/library/custominterp.html
/library/traceback.html
/library/gc.html
/library/io.html
/library/markup.html
/library/tokenize.html
/library/framework.html
/library/chunk.html
/library/bz2.html
/library/textwrap.html
/library/colorsys.html
/library/future_builtins.html
/library/fcntl.html
/library/abc.html
/library/fm.html
/library/zipimport.html
/library/crypt.html
/library/sha.html
/library/tarfile.html
/library/__builtin__.html
/library/robotparser.html
/library/language.html
/library/sunau.html
/library/archiving.html
/library/exceptions.html
/library/inspect.html
/library/gl.html
/library/cookie.html
/library/internet.html
/library/netrc.html
/library/parser.html
/library/xml.dom.minidom.html
/library/fnmatch.html
/library/glob.html
/library/someos.html
/library/token.html
/library/heapq.html
/library/unittest.html
/library/sysconfig.html
/library/wave.html
/library/pydoc.html
/library/fl.html
/library/ast.html
/library/cgi.html
/library/curses.ascii.html
/library/commands.html
/library/macpath.html
/library/csv.html
/library/fileformats.html
/library/user.html
/library/pipes.html
/library/dummy_thread.html
/library/msilib.html
/library/errno.html
/library/pprint.html
/library/stdtypes.html
/library/numbers.html
/library/socket.html
/library/dis.html
/library/miniaeframe.html
/library/pty.html
/library/logging.config.html
/library/smtplib.html
/library/macostools.html
/c-api/init.html
/c-api/sequence.html
/c-api/object.html
/c-api/exceptions.html
/c-api/number.html
/c-api/objbuffer.html
/c-api/veryhigh.html
/c-api/memory.html
/c-api/marshal.html
/c-api/abstract.html
/c-api/structures.html
/c-api/arg.html
/c-api/mapping.html
/c-api/intro.html
/c-api/gcsupport.html
/c-api/codec.html
/c-api/objimpl.html
/_sources/c-api/index.txt
/extending/embedding.html
/c-api/reflection.html
/c-api/refcounting.html
/c-api/utilities.html
/c-api/iter.html
/c-api/conversion.html
/c-api/allocation.html
/c-api/concrete.html
/c-api/sys.html
/c-api/typeobj.html
/c-api/import.html
/_sources/license.txt
/distutils/index.html
/faq/windows.html
/faq/extending.html
/howto/argparse.html
/faq/installed.html
/faq/programming.html
/faq/general.html
/faq/library.html
/faq/design.html
/_sources/faq/index.txt
/faq/gui.html
/genindex-L.html
/genindex-R.html
/genindex-U.html
/genindex-M.html
/genindex-A.html
/genindex-W.html
/genindex-J.html
/genindex-B.html
/genindex-Symbols.html
/genindex-Z.html
/genindex-D.html
/genindex-I.html
/genindex-Q.html
